### ISSUE TITLE
Query: Population from largest to smallest

### ISSUE THREAD

**Issue by decfisher** [decfisher/Napier-GA-Group-H#1]
1. All the countries in the **world** organised by largest population to smallest.
2. All the countries in a **continent** organised by largest population to smallest.
3. All the countries in a **region** organised by largest population to smallest.

**Comment by Tide44-cmd** [comment]
As A member of organization x
I Want to view all countries in the world by population largest to smallest
So That I can see which country has the largest population in the world

As A member of organization x
I Want to view all countries in a given Continent by population largest to smallest
So That I can see which country has the largest population in the Continent

As A member of organization x
I Want to view all countries in a Region by population largest to smallest
So That I can see which country has the largest population in the Region

**Acceptance Criteria**:
Given I run the query
When I have provided no parameters
Then I will see the countries listed in the world from largest to smallest

Given I run the query
When I have provided 1 parameter
Then I will see the countries listed in the Continent from largest to smallest

Given I run the query
When I have provided 2 parameters
Then I will see the countries listed in the Region from largest to smallest

********************************************************************************
The query should filter the results using parameters provided by the user in order to display what the user requires to see.
