### ISSUE TITLE
Query: Populations of a given parameter

### ISSUE THREAD

**Issue by decfisher** [decfisher/Napier-GA-Group-H#15]
- The population of the **world**
- The population of a **continent**
- The population of a **region**
- The population of a **country**
- The population of a **district**
- The population of a **city**

**Comment by Tide44-cmd** [comment]
As A member of organization x
I Want a report that will give me the population when no parameter is provided
So That I can see the population of the **world**

As A member of organization x
I Want a report that will give me the population when 1 parameter is provided
So That I can see the population of the **continent**

As A member of organization x
I Want a report that will give me the population when 2 parameters are provided
So That I can see the population of the **region**

As A member of organization x
I Want a report that will give me the population when 3 parameters are provided
So That I can see the population of the **country**

As A member of organization x
I Want a report that will give me the population when 4 parameters are provided
So That I can see the population of the **district**

As A member of organization x
I Want a report that will give me the population when 5 parameters are provided
So That I can see the population of the **city**


Acceptance Criteria:
Given I run the query
When I have provided no parameters
Then I will see the population of the **world**

Given I run the query
When I have provided 1 parameter
Then I will see the population of the **continent**

Given I run the query
When I have provided 2 parameters
Then I will see the population of the **region**

Given I run the query
When I have provided 2 parameters
Then I will see the population of the **country**

Given I run the query
When I have provided 2 parameters
Then I will see the population of the **district**

Given I run the query
When I have provided 2 parameters
Then I will see the population of the **city**
