### ISSUE TITLE
Query: Organise cities by population from largest to smallest

### ISSUE THREAD

**Issue by decfisher** [decfisher/Napier-GA-Group-H#3]
1. All the cities in the **world** organised by largest population to smallest.
2. All the cities in a **continent** organised by largest population to smallest.
3. All the cities in a **region** organised by largest population to smallest.
4. All the cities in a **country** organised by largest population to smallest.
5. All the cities in a **district** organised by largest population to smallest.

**Comment by 40517473** [comment]
As a member of organization x
I want to view all cities in the world by population largest to smallest
So that I can see which capital city has the largest population in the World

As a member of organization x
I want to view all cities in a given Continent by population largest to smallest
So that I can see which city has the largest population in the Continent

As a member of organization x
I want to view all cities in a Region by population largest to smallest
So that I can see which city has the largest population in the Region

As a member of organization x
I want to view all cities in a Country by population largest to smallest
So that I can see which city has the largest population in the Country

As a member of organization x
I want to view all cities in a District by population largest to smallest
So that I can see which city has the largest population in the District

Acceptance Criteria:
Given I run the query
When I have provided no parameters
Then I will see the cities listed in the World from largest to smallest

Given I run the query
When I have provided 1 parameter
Then I will see the cities listed in the Continent from largest to smallest

Given I run the query
When I have provided 2 parameters
Then I will see the cities listed in the Region from largest to smallest

Given I run the query
When I have provided 3 parameters
Then I will see the cities listed in the Country from largest to smallest

Given I run the query
When I have provided 4 parameters
Then I will see the cities listed in the District from largest to smallest
