### ISSUE TITLE
Query: Organise capital cities by population from largest to smallest

### ISSUE THREAD

**Issue by decfisher** [decfisher/Napier-GA-Group-H#5]
1. All the capital cities in the **world** organised by largest population to smallest.
2. All the capital cities in a **continent** organised by largest population to smallest.
3. All the capital cities in a **region** organised by largest to smallest.

**Comment by Tide44-cmd** [comment]
As A member of organization x
I Want to view all **capital cities** in the **world **by population largest to smallest
So That I can see which **capital city** has the largest population in the **world**

As A member of organization x
I Want to view all **capital cities** in a given **Continent **by population largest to smallest
So That I can see which **capital city** has the largest population in the **Continent**

As A member of organization x
I Want to view all **capital cities** in a **Region **by population largest to smallest
So That I can see which **capital city** has the largest population in the **Region**

Acceptance Criteria:
Given I run the query
When I have provided no parameters
Then I will see the **capital cities** listed in the **world **from largest to smallest

Given I run the query
When I have provided 1 parameter
Then I will see the **capital cities** listed in the **Continent **from largest to smallest

Given I run the query
When I have provided 2 parameters
Then I will see the **capital cities** listed in the **Region **from largest to smallest

**Comment by Tide44-cmd** [comment]
Queries created for this functionality
2 New Methods written

getCapitalCitiesByPopulation
This Method can accept 0, 1, or 2 parameters and will return the list of Capital Cities from largest to smallest
e.g.
getCapitalCitiesByPopulation("Asia","Eastern Asia")

printCapCities()
This Method will print a list of Capital Cities provided to it. The columns included depends on the query run.
