### ISSUE TITLE
Query: Top N populated capital cities

### ISSUE THREAD

**Issue by decfisher** [decfisher/Napier-GA-Group-H#6]
1. The top `N` populated capital cities in the **world** where `N` is provided by the user.
2. The top `N` populated capital cities in a **continent** where `N` is provided by the user.
3. The top `N` populated capital cities in a **region** where `N` is provided by the user.

**Comment by 40517473** [comment]
As a member of organisation X
I want to view the top N populated capital cities in the world
So that I can identify the top N most populous capital cities in the world

As a member of organisation X
I want to view the top N populated capital cities in a continent
So that I can identify the top N most populous capital cities in the continent

As a member of organisation X
I want to view the top N populated capital cities in a region
So that I can identify the top N most populous capital cities in a region

Acceptance Criteria
Given I run the query
When I provide 1 parameter (N)
Then I will see a list of the top N capital cities in the world and their population

Given I run the query
When I provide 2 parameters (N and a continent)
Then I will see a list of the top N capital cities in a continent and their population

Given I run the query
When I provide 2 parameters (N and a region)
Then I will see a list of the top N capital cities in a region and their population

The query should filter the results using parameters provided by the user in order to display what the user requires to see.
